name: Build
run-name: Build next.js app

permissions:
  contents: read

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: "20"
          cache: yarn

      - name: Restore cache
        uses: actions/cache@v6
        with:
          path: |
            .next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('src/**.[jt]s', 'src/**.[jt]sx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-
            ${{ runner.os }}-nextjs-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build next.js app
        run: yarn build
